version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: resilience-poc-rabbitmq-dev
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq

  redis:
    image: redis:7-alpine
    container_name: resilience-poc-redis-dev
    restart: always
    ports:
      - "6379:6379"

  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: resilience-poc-wiremock-dev
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - ./testing/wiremock/mappings:/home/wiremock/mappings
      - ./testing/wiremock/__files:/home/wiremock/__files
    command: --verbose --global-response-templating


volumes:
  rabbitmq_data:
  rabbitmq_log:
