spring:
  application:
    name: resilience-patterns-poc

  cloud:
    openfeign:
      client:
        config:
          # Configuración global para TODOS los clientes
          default:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: basic

          # Configuración específica para external-api
          external-api:
            connect-timeout: 5000
            read-timeout: 10000
            logger-level: full


  rabbitmq:
    host: localhost
    port: 5672
    ssl:
      enabled: false
    username: admin
    password: admin
    virtual-host: /
    connection-timeout: 10s


  cache:
    type: simple  # Cache en memoria (no Redis)
    cache-names: external-api-cache

# ============================================
# RESILIENCE4J - CONFIGURACIÓN
# ============================================
resilience4j:
  ratelimiter:
    instances:
      external-api:
        limit-for-period: 20                # 20 peticiones # Más permisivo para async 100
        limit-refresh-period: 60s           # por minuto
        timeout-duration: 30s               # Espera hasta 30s por slot
        register-health-indicator: true

  circuitbreaker:
    instances:
      external-api:
        # Configuración del estado CLOSED -> OPEN
        failure-rate-threshold: 50          # 50% de fallos para abrir  # Más sensible para proteger sistema async 30
        minimum-number-of-calls: 5          # Mínimo 5 llamadas para evaluar  # Menos llamadas para evaluar en async 3
        sliding-window-size: 10             # Ventana de 10 llamadas
        sliding-window-type: count_based    # Basado en cantidad, no tiempo

        # Configuración del estado OPEN -> HALF_OPEN
        wait-duration-in-open-state: 30s                  # Esperar 30s antes de probar
        permitted-number-of-calls-in-half-open-state: 3   # 3 pruebas para cerrar

        # Otras opciones a considerar
        # Configuración del estado HALF_OPEN -> CLOSED
        slow-call-rate-threshold: 100       # 100% de llamadas lentas
        slow-call-duration-threshold: 5s    # Llamada lenta > 5s

        # Excepciones que NO abren el circuit
        ignore-exceptions:
          - java.lang.IllegalArgumentException

        # Métricas y eventos
        register-health-indicator: true
        event-consumer-buffer-size: 10

  retry:
    instances:
      external-api:
        max-attempts: 3                     # Máximo 3 intentos
        wait-duration: 1s                   # Esperar 1s entre intentos
        exponential-backoff-multiplier: 2   # Backoff exponencial
        retry-exceptions:                   # Solo reintentar estas excepciones
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.FeignException            # TEMPORAL POR PRUEBASS
        ignore-exceptions:                  # NO reintentar estas
          - java.lang.IllegalArgumentException


# ============================================
# API EXTERNAL (MOCK) - CONFIGURATION
# ============================================
external-api:
  base-url: http://localhost:8081
  endpoints:
    users: /api/users
    orders: /api/orders


# ============================================
# LOGGING PARA DEBUG
# ============================================
logging:
  level:
    com.resiliencepatterns.poc: INFO

    io.github.resilience4j: WARN
    io.github.resilience4j.retry: DEBUG
    io.github.resilience4j.circuitbreaker: INFO
    io.github.resilience4j.ratelimiter: INFO
    org.springframework.aop: WARN
    org.springframework.boot.autoconfigure.aop: WARN

    feign: INFO
    org.springframework.retry: INFO


# ============================================
# ACTUATOR - MONITOREO Y MÉTRICAS
# ============================================
management:
  endpoints:
    web:
      exposure:
        include: health,metrics,circuitbreakers,ratelimiters,retries
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
    redis:
      enabled: false